# Use an official Node.js image as the base image
FROM node:20-alpine

# Set the working directory to root
WORKDIR /app

# Copy package.json and package-lock.json (if available)
COPY package*.json ./

# Install Node.js dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the port the app runs on
EXPOSE 3333

# Run migrations
RUN npm run build

# Serve the app
CMD ["npm", "run", "dev"]